# Generated by Django 4.2.4 on 2023-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_snack_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
