# Generated by Django 4.2.4 on 2023-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_snack_description_alter_snack_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
