# Generated by Django 4.2.4 on 2023-08-15 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_snack_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='files/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('categoty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.categoty')),
            ],
        ),
        migrations.DeleteModel(
            name='Beer',
        ),
        migrations.DeleteModel(
            name='Snack',
        ),
        migrations.AddField(
            model_name='picture',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
