# Generated by Django 4.2.4 on 2023-08-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_categoty_picture_staff_delete_beer_delete_snack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
